### PR TITLE
Auto - Purchaser

### PR DESCRIPTION
**Pull request by gapple**
This updates #48 by @russeli to apply on the latest master

### CODE REVIEW

**Comment by russeli** [comment]
The buyUpgrade function should be edited to following to support purchasing elements in future:

```
var buyUpgrade = function(id) {
    if(id >= 3 && 6 >= id) { //If upgrade is element damage
        g_Minigame.CurrentScene().TryUpgrade(document.getElementById('upgr_' + id).childElements()[3]);
    } else {
        g_Minigame.CurrentScene().TryUpgrade(document.getElementById('upgr_' + id).childElements()[0].childElements()[1]);
    }
}
```

I won't bother forking this just to make the update. :)

**Comment by russeli** [comment]
I'm not familiar with Greasemonkey or Tampermonkey, but if it does update the script automatically without notifying or asking the user for confirmation, the initial value of `avgClicksPerSecond`
should be set to 1(?) before merging, so that the impact on the users is minimized.
For example the script might start upgrading click damage, even though the user doesn't click at all.

**Comment by win0na** [comment]
GM / TM checks in various intervals to see if it can update the script. If it does, the user has to refresh the minigame for the changes to take effect.

**Comment by sithrebel15** [comment]
I've been running this all day. It works fine. Have you implemented the tier four upgrades though?

**Comment by russeli** [comment]
No implementing was required, it works based on the upgrade type.

**Comment by gapple** [comment]
:+1: I was surprised and delighted to find that I already had a few levels of AFK Equipment purchased.

## 

It's a small matter, but when respawning it looked like the script purchased shields a few times due to health being 0, until the respawn kicked in.  My thought is setting a flag so that only one shield purchase happens per respawn.

**Comment by russeli** [comment]
The same probably happens at any point when health is lower than 30%. So let's say flag is raised when hp hits below 30%. When do you reset the flag? You could reset it when you press respawn, but how about in cases where hp is lower than 30% but greater than 0.

Other solution could be checking a flag wether we have died and only buying armor in that case. Though then the armor would get upgraded less frequently adding more load to medics etc.

PS. I pushed one fix

**Comment by gapple** [comment]
The [reddit guide](https://www.reddit.com/r/Steam/comments/39i0qc/psa_how_the_monster_game_works_an_indepth/) mentions that buying armor automatically fills HP, so that shouldn't be an issue.

**Comment by russeli** [comment]
I now added Lucky Shot to calculations, according to some sources autoattacks don't crit so I left their calculations untouched.  
EDIT: Made new pull request for this one(#86)

**Pull request merged**
