### PR TITLE
Greasemonkey fixes

### PR DESCRIPTION
**Pull request by welwood08**
Just a couple of minor changes to the Greasemonkey headers to make it work. @grant is required, and sometimes the page loads with 2 /'s in the URL.

Also renamed the file so that Greasemonkey offers to install it directly from the raw URL.

### CODE REVIEW

**Comment by DarkLordJack** [comment]
You can't refuse all permissions to the script as that doesn't allow it to do anything.

**Comment by Eriner** [comment]
@DarkLordJack The script doesn't use any GreaseMonkey API calls, so '@grant none' is correct. See: http://wiki.greasespot.net/API_Reference and http://wiki.greasespot.net/@grant

**Comment by Eriner** [comment]
@welwood08 you need up update the URLs for '@updateURL' and '@downloadURL'

**Comment by sithrebel15** [comment]
@welwood08 Yes I saw that hence why I deleted the comment. Oddly enough your version doesn't work for me when grant none is included though.

**Comment by welwood08** [comment]
@Eriner Thanks for catching that, should've been part of the blind find+replace. :)

**Comment by Eriner** [comment]
@welwood08 no problem, made a pull at https://github.com/welwood08/steamSummerMinigame/pull/1

**Comment by welwood08** [comment]
Ah, didn't see that in time so we've made the same change.

**Comment by mouseas** [comment]
Will this change (renaming the file) break auto-update for people who've already installed it in GM/TM?

**Comment by welwood08** [comment]
I hadn't thought of that, but yes. :(

**Comment by welwood08** [comment]
Is there any way to make symlinks in git that persist on GitHub?

**Comment by mouseas** [comment]
I'm thinking switch the file name back, and add a small GM/TM file `autoPlay.user.js` which just goes to https://raw.githubusercontent.com/mouseas/steamSummerMinigame/master/autoPlay.js and loads it. That would leave the script working for existing GM/TM users, and it would fulfil the "automatically update the manual script" TODO item.

**Comment by welwood08** [comment]
That I can also do, although how are you going to handle user customisation of the option variables?

**Comment by mouseas** [comment]
How does customization currently happen for *monkey? I assumed users who wanted to tweak the script simply modified the code.

**Comment by welwood08** [comment]
Right, but you're suggesting the main script code would now be loaded direct from the GitHub URL, with those option variables overwriting anything set in the userscript.

**Comment by mouseas** [comment]
Fair point. Suggestions?

**Comment by welwood08** [comment]
I'm not sure - at least in Greasemonkey the userscript context is supposed to be sandboxed, which makes reading variables from the page context tricky anyway.

**Comment by mouseas** [comment]
What about doing it the other way around? Writing a script at `autoplay.js` that loads `autoplay.user.js`? Would that work any better, or would the same problems exist?

**Comment by win0na** [comment]
It would have to be the other way around, with `autoPlay.user.js` loading `autoPlay.js`. That way, `autoPlay.user.js` can act as a wrapper, with `autoPlay.js` including all of the automation that it already has.

**Comment by win0na** [comment]
Or, to save trouble, just rename the current `autoPlay.js` to `autoPlay.user.js` so that we don't have to deal with wrapping technology. From what I've been looking at, wrapping is nearly impossible with TM / GM because both rely on one file only. By renaming it, we solve that issue.

However, by doing said renaming, everyone who is currently using the GM / TM script will have to go back to this repository and re-add the script.

I have a solution for this. We rename the file to include `.user.js` as said above, and add a new file called `autoPlay.js` (since the actual script will now be called `autoPlay.user.js`). Then, in the new file, we just put an alert or redirect to this repository telling them to re-add the file so they are updated on the `autoPlay.user.js` file.

If that is confusing, I can by all means demonstrate it for you.

**Comment by mouseas** [comment]
@Winneon Looks like a good solution to me.

**Comment by win0na** [comment]
The above solution has been implemented. If there are any other issues, feel free to make a pull request. Most pull requests that are currently in the queue will receive merge conflicts because of the file name change. This is addressed in the README.

**Pull request closed without merging**
