### PR TITLE
Implemented an efficient auto-clicker

### PR DESCRIPTION
**Pull request by Contex**
See commit comment below.

### CODE REVIEW

**Comment by win0na** [comment]
I thought the creator of this script repeated multiple times that there will be no such auto-clicker in this script because it leans into the area of "cheating".

**Comment by Contex** [comment]
@Winneon I was under the assumption that it was related to efficiency issues, if not then feel free to close the PR @mouseas.

**Comment by mouseas** [comment]
Winneon is right. I'm not including an auto-clicker. I'm trying to keep this script within the realm of what an active player would do, and what is unlikely to cause Valve to react and change their game. However, I would be glad to have auto-clicking (about 5/sec) only while Raining Gold is active in the current lane. If you come up with that, I'll gladly add it in.

**Comment by Contex** [comment]
That's fully understandable.

And that should be doable, this can easily be done by checking this array:

```
window.g_Minigame.CurrentScene().m_rgGameData.lanes[window.g_Minigame.CurrentScene().m_rgPlayerData.current_lane].active_player_abilities
```

Example object in the array:

```
ability: 16
accountid_caster:133872584
multiplier: 1
timestamp_done: 1434156949
```

Array is empty if there are no active abilities in the lane so all you'd have to check for in that array is ability 17 and then switch to that specific lane.

I'll see if I can get that done tomorrow, have to head off for now.

**Pull request closed without merging**
