### PR TITLE
Added autoclick textfield option. Makes way for other options

### PR DESCRIPTION
**Pull request by ghost**
Integrating this nice feature from https://github.com/SteamDatabase/steamSummerMinigame. The first of what will surely be many.

### CODE REVIEW

**Comment by ghost** [comment]
Also, this addresses this issue: https://github.com/mouseas/steamSummerMinigame/issues/79#issuecomment-111870551

**Comment by ZedTheYeti** [comment]
I played with it a little and their seems to be some bugs in it. Can we got some other people to test this out? It didn't seem to be setting the number correctly, and at one point it ignored the number all together and clicked really really fast.

**Comment by ghost** [comment]
Hmm I made sure to test it quite thoroughly, did you press enter after changing the number?

**Comment by ZedTheYeti** [comment]
I did, it may have just been a problem my end. If we got one other person to test it I'll merge it. Just to be sure.

**Comment by mouseas** [comment]
I tested it, made several tweaks until it was working nicely. Commit 6370ebeeeacd6dcaaa44c475ecd17057db3dadb7 which unfortunately doesn't include @JCKE's commit history. (Sorry, JCKE)

**Comment by ghost** [comment]
No problem, just happy to help

**Pull request closed without merging**
