### PR TITLE
Prevents blowing up bosses and treasures

### PR DESCRIPTION
**Pull request by Ruzihm**

### CODE REVIEW

**Comment by Ruzihm** [comment]
Also added functions to enable or disable items as well as check if they are already enabled or disabled.

**Comment by mouseas** [comment]
Is this trying to prevent other players from using abilities, or just the player using the script?

**Comment by Ruzihm** [comment]
Anybody using the script. (ideally which would be everyone ;) )

no weird communication if that's what you mean. just disables the buttons in the ui while in a boss lane.

**Comment by mouseas** [comment]
Kk. I will review it and merge it in when I get time.

**Pull request merged**
