### PR TITLE
Disable enemy flinching animation

### PR DESCRIPTION
**Pull request by Contex**
Additional improvement on #17

Edit: the monsters (enemies, spawners and bosses) will stay in their idle position after they spawn until they die.

### CODE REVIEW

**Comment by mouseas** [comment]
Have you checked that this doesn't cause errors in the game's code?

**Comment by Contex** [comment]
Tested it on Chrome and FF (both worked), I couldn't get the game running at all on IE.

**Comment by Contex** [comment]
Memory consumption is down to around 385 MB for me now, but it's slowly increasing. That's with an auto-clicker running 15 times per second.

**Comment by mouseas** [comment]
Merged in. Out of curiosity, without disabling flinching, how much memory does it use? Seems like flinching wouldn't use anywhere near as much memory as particles.

**Comment by Contex** [comment]
@mouseas I honestly don't know, and I'm not able to test it at the moment, I might do so tomorrow just out of curiosity. I reckon that it does affect it a bit when you're using an auto-clicker, but nowhere as much as the particles, that's for sure.

**Pull request merged**
