### PR TITLE
Add Steal Health and only use it if medic is not active.

### PR DESCRIPTION
**Pull request by drantor**
Only use god mode if no other heal skill is running and fix isAbilityActive.

### CODE REVIEW

**Comment by mouseas** [comment]
The logic doesn't look right. It should use Medics if it's available regardless of availability of Steal Health or God Mode. If Medics is not available but Steal Health is, and Medics is not active in the lane, then Steal Health should be used. If neither Medics nor Steal Health is available, and neither is currently active in the lane, then God Mode should be used.

**Comment by drantor** [comment]
Okay should be fine now.
1. Always use Medic
2. Use Steal Health when Medic is not active on current line
3. Use God Mode when neither Medic nor Steal Health is active on current line

Still have to test but they went into server maintenance

**Comment by mouseas** [comment]
I need 1 person to independently test this for errors and functionality.

**Comment by win0na** [comment]
There are merge conflicts in this pull request due to the filename change. Ignore them. I'll resolve them when the time has come for this to be merged with the master branch.

**Comment by ghost** [comment]
I believe this can be closed, as the features have been implemented elsewhere

**Comment by ZedTheYeti** [comment]
Alright, closing.

**Pull request closed without merging**
