### PR TITLE
Auto purchase badge point rewards

### PR DESCRIPTION
**Pull request by ghost**
Auto-purchases the badge point rewards for you. Right now, it is prioritized based on percentages, i.e. ability 1 gets ~= 10% of purchases, ability 2 gets ~= 8%, etc.

Also changed the `hasItem()` function to `numItem()`, returning a number instead of a boolean.

I won't be back on for a few hours, but hopefully you guys can give it a test.

### CODE REVIEW

**Comment by ghost** [comment]
Also, something ugly happened when I merged upstream. At least it's testable right now

**Comment by win0na** [comment]
I can fix the merge issues easily. The only way to test this however is wait until the rooms reset tomorrow.

**Comment by ghost** [comment]
Well, one way to test is quit and take the badge points to another game, I've been doing this with a throwaway account. But yeah, thorough testing can't happen until tomorrow.

**Comment by ghost** [comment]
Tested this out this morning, works perfect! The distribution amongst the items could be tweaked, however

**Pull request merged**
