### PR TITLE
Adding getCooldownTime()

### PR DESCRIPTION
**Pull request by BryghtShadow**

### CODE REVIEW

**Comment by ghost** [comment]
While you're adding this, could you please re-add the functions I mentioned here: https://github.com/mouseas/steamSummerMinigame/issues/97#issuecomment-112204429?

**Comment by BryghtShadow** [comment]
Sure thing.

**Comment by ZedTheYeti** [comment]
Are these used anywhere or are we adding convenience functions? I'll merge it either way, just curious.

**Comment by ghost** [comment]
`updateAvgClickRate()` isn't used yet, but in the future I will be adding this to the calculation for purchasing click upgrades. It seems as though `disableFlinchingAnimation()` and `disableDamageText()` were intended to make `firstRun()` a bit cleaner, maybe I'll use them when I add the toggle options from https://github.com/SteamDatabase/steamSummerMinigame

**Comment by ZedTheYeti** [comment]
Alright well they're back in there.Thanks!

**Pull request merged**
